name: Deploy Application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests Before Deploy
        run: node node_modules/jest/bin/jest.js

      - name: Simulate Deployment with Fake Secret
        env:
          FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
        run: |
          echo "🚀 Deploying application..."
          echo "Using fake secret: $FAKE_SECRET"
          echo "✅ Deployment simulation complete!"
